version: '3'
services:
  mysql-standalone:
    image: mysql:latest
    environment:
      MYSQL_USER: 'service_user'
      MYSQL_PASSWORD: 'service_user_password'
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'user_service_schema'
    ports:
      - 3306:3306
#    expose:
#      - 3306
#    networks:
#      - user-service-network

  user-service-spring:
    image: davehatton/user_service
    build:
      context: .
#    expose:
#      - 8080
#      - 3306
    ports:
    - 8080:8080
#    - 3306:3306
    depends_on:
      - mysql-standalone
    restart: always
    links:
      -   mysql-standalone
#    networks:
#      - user-service-network

#networks:
#  user-service-network:
#    driver: bridge
    

